name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.4
  sizer: ^2.0.13
  crypto: ^3.0.1
  like_button: ^2.0.2
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.4
  cloud_functions: ^3.0.3
  cupertino_icons: ^1.0.2
  google_fonts: any
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  image_picker: ^0.8.1+3
  url_launcher: ^6.0.9
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  photo_view: ^0.13.0
  photo_manager: ^1.3.4
  linkable: ^3.0.1
  font_awesome_flutter: ^9.1.0
  carousel_slider: ^4.0.0
  video_player: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/splash.png
  - assets/auth.png
  - assets/apple.png
  - assets/google.png
